module.exports = {
    UI_MODES: Object.freeze({
        STANDALONE: 0,
        LED_ARRAY: 1
    }),
    LED_COLORS: [
        "White",
        "Black",
        "Red",
        "Orange",
        "Yellow",
        "Green",
        "Teal",
        "Cyan",
        "Blue",
        "Magenta",
        "Purple",
        "Pink"
    ],
    ALL_COLORS: [
        "White",
        "Black",
        "Red",
        "Orange",
        "Yellow",
        "Green",
        "Teal",
        "Cyan",
        "Blue",
        "Magenta",
        "Purple",
        "Pink",
        "Lime",
        "Olive",
        "Navy",
        "Maroon",
        "Gold",
        "Coral",
        "Salmon",
        "Crimson",
        "Khaki",
        "Lavender",
        "Turquoise",
        "Indigo",
        "DarkSlateGray",
        "MediumOrchid",
        "LightSkyBlue",
        "DodgerBlue",
        "Chocolate",
        "DarkGoldenrod"
    ]
};