import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SketchGrid from "../components/SketchGrid";
import Link from "next/link";

export default function Home() {
  const [gridSize, setGridSize] = React.useState({ width: 30, height: 30 });

  const updateGrid = (event) => {
    const { name, value } = event.target;

    setGridSize({ ...gridSize, [name]: value });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Pixel Sketch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/pixel-sketch">
        <a>Pixel Sketch</a>
      </Link>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
