import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import SketchGrid from "../components/SketchGrid";
import { Container } from "@mui/material";
import { height } from "@mui/system";
import GridRow from "../components/GridRow/GridRow";

const getGrid = (rows, columns) => {
  const grid = {};

  for (let i = 0; i < rows; i++) {
    grid[i] = new Array(columns).fill("#FFF");
  }

  return grid;
};

export default function PixelSketch() {
  const [rows, columns] = [16, 16];
  const [sketchGrid, setSketchGrid] = React.useState(getGrid(rows, columns));
  const [selectedColor, setSelectedColor] = React.useState("#000");

  // const updateGrid = (row, column, ) => {
  //   const currentRow = [...sketchGrid[row]];

  //   currentRow[column] =
  // };

  const getSketchGrid = () => {
    const gridRows = [];
    for (let i = 0; i < rows; i++) {
      gridRows.push(<GridRow index={i} columns={columns} />);
    }

    return gridRows;
  };

  console.log(sketchGrid);

  return (
    <div className={styles.container}>
      <Head>
        <title>Pixel Sketch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1> Sketch Grid</h1>
      {getSketchGrid()}
    </div>
  );
}
