import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import SketchGrid from "../components/SketchGrid";
import { Container } from "@mui/material";

export default function PixelSketch() {
  const [gridSize, setGridSize] = React.useState({ columns: 10, rows: 10 });

  const updateGrid = (event) => {
    const { name, value } = event.target;

    setGridSize({ ...gridSize, [name]: value });
  };

  return (
    <Container className={styles.container}>
      <Head>
        <title>Pixel Sketch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1> Sketch Grid</h1>
      <SketchGrid columns={gridSize.columns} rows={gridSize.rows} />
      <h1>Board Size</h1>
      <input
        type={"number"}
        min={1}
        max={100}
        value={gridSize.columns}
        name={"columns"}
        onChange={updateGrid}
      />
      X
      <input
        type={"number"}
        min={1}
        max={100}
        value={gridSize.rows}
        name={"rows"}
        onChange={updateGrid}
      />
    </Container>
  );
}
