import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import SketchGrid from "../components/SketchGrid";

export default function PixelSketch() {
  const [gridSize, setGridSize] = React.useState({ width: 10, height: 10 });

  const updateGrid = (event) => {
    const { name, value } = event.target;

    setGridSize({ ...gridSize, [name]: value });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Pixel Sketch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SketchGrid width={gridSize.width} height={gridSize.height} />
      <h1>Board Size</h1>
      <input
        type={"number"}
        min={1}
        max={100}
        value={gridSize.width}
        name={"width"}
        onChange={updateGrid}
      />
      X
      <input
        type={"number"}
        min={1}
        max={100}
        value={gridSize.height}
        name={"height"}
        onChange={updateGrid}
      />
    </div>
  );
}
